/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SEALWrapper */

#ifndef _Included_SEALWrapper
#define _Included_SEALWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SEALWrapper
 * Method:    encryptMessage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SEALWrapper_encryptMessage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
